name: 'Run Build'

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

jobs:
  run-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Run build
        run: npm run build
